import React,{useMemo,useState} from 'react';
import {Briefcase,Users,MessageCircle,Bell,Plus,ChevronRight,MapPin,IndianRupee,ShieldCheck} from 'lucide-react';

const initialJobs=[
 {id:'E-001',title:'Waiter',location:'Andheri East',vacancies:4,applicants:18,status:'Active',payment:'Paid'},
 {id:'E-002',title:'Kitchen Helper',location:'Powai',vacancies:2,applicants:7,status:'Active',payment:'Paid'},
 {id:'E-003',title:'Delivery Executive',location:'Bandra West',vacancies:8,applicants:0,status:'Draft',payment:'Pending'}
];
const initialTeam=[{id:'T-001',name:'Owner',email:'owner@company',role:'Owner',access:'Full access'},{id:'T-002',name:'Rahul Sharma',email:'manager@company',role:'Manager',access:'Jobs + Candidates + Chat'}];

export default function EmployerDashboard(){
 const [jobs,setJobs]=useState(initialJobs); const [tab,setTab]=useState('overview'); const [team,setTeam]=useState(initialTeam);
 const active=useMemo(()=>jobs.filter(j=>j.status==='Active').length,[jobs]); const applicants=useMemo(()=>jobs.reduce((n,j)=>n+j.applicants,0),[jobs]);
 return <div className="employerShell">
  <header className="employerHeader"><div><div className="employerBrand">Mumbai Jobz</div><div className="employerSub">Employer Dashboard</div></div><div className="employerActions"><button><Bell size={19}/><span>3</span></button><div className="avatar">HR</div></div></header>
  <section className="welcome"><div><p>Good morning</p><h1>Premium Family Restaurant</h1><span>Andheri East · 1 branch</span></div><button className="postBtn" onClick={()=>setTab('post')}><Plus size={18}/> Post a Job</button></section>
  <div className="dashboardNav">{[['overview','Overview',Briefcase],['jobs','My Jobs',Briefcase],['candidates','Candidates',Users],['messages','Chat',MessageCircle],['team','Team',ShieldCheck]].map(([id,label,Icon])=><button className={tab===id?'selected':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}</button>)}</div>
  {tab==='overview'&&<><section className="stats"><div><Briefcase/><b>{active}</b><span>Active jobs</span></div><div><Users/><b>{applicants}</b><span>Total applicants</span></div><div><MessageCircle/><b>6</b><span>Candidates approached</span></div><div><IndianRupee/><b>₹300</b><span>Per job listing</span></div></section><section className="dashSection"><div className="dashTitle"><div><h2>Hiring now</h2><p>Manage your active positions</p></div><button onClick={()=>setTab('jobs')}>View all <ChevronRight size={16}/></button></div>{jobs.filter(j=>j.status==='Active').map(j=><JobRow job={j} key={j.id}/>)}</section><section className="quick"><h2>Quick actions</h2><div><button onClick={()=>setTab('post')}><Plus/>Post a new job</button><button onClick={()=>setTab('candidates')}><Users/>Find candidates</button><button onClick={()=>setTab('messages')}><MessageCircle/>Open chat</button><button onClick={()=>setTab('team')}><ShieldCheck/>Manage team</button></div></section></>}
  {tab==='jobs'&&<section className="dashSection page"><div className="dashTitle"><div><h2>My Jobs</h2><p>All positions and payment status</p></div><button className="postBtn" onClick={()=>setTab('post')}><Plus size={17}/> Post Job</button></div>{jobs.map(j=><JobRow job={j} key={j.id}/>)}</section>}
  {tab==='candidates'&&<section className="dashSection page"><div className="dashTitle"><div><h2>Candidates</h2><p>Applicants and people you've approached</p></div></div><div className="candidateBox"><Users size={30}/><div><b>Candidate pipeline</b><p>Review applicants, shortlist candidates and approach them without sharing personal WhatsApp numbers.</p></div></div></section>}
  {tab==='messages'&&<section className="dashSection page"><div className="dashTitle"><div><h2>Chat</h2><p>Keep recruitment conversations inside Mumbai Jobz</p></div></div><div className="candidateBox"><MessageCircle size={30}/><div><b>Recruitment inbox</b><p>Candidate and manager conversations will appear here.</p></div></div></section>}
  {tab==='team'&&<Team team={team} setTeam={setTeam}/>} {tab==='post'&&<PostJob onBack={()=>setTab('overview')} onCreate={job=>{setJobs(j=>[...j,{...job,id:`E-${String(j.length+1).padStart(3,'0')}`,applicants:0,status:'Draft',payment:'Pending'}]);setTab('jobs')}}/>}
 </div>
}
function JobRow({job}){return <article className="jobRow"><div className="jobBadge"><Briefcase size={20}/></div><div className="jobInfo"><div><h3>{job.title}</h3><em className={job.status==='Active'?'live':''}>{job.status}</em></div><p><MapPin size={13}/>{job.location} · {job.vacancies} vacancies</p><small>{job.applicants} applicants · Payment {job.payment}</small></div><ChevronRight size={18}/></article>}
function Team({team,setTeam}){const [name,setName]=useState('');const [email,setEmail]=useState('');return <section className="dashSection page"><div className="dashTitle"><div><h2>Team & Managers</h2><p>Give trusted staff access without sharing the owner login.</p></div></div>{team.map(t=><article className="jobRow" key={t.id}><div className="jobBadge"><ShieldCheck size={20}/></div><div className="jobInfo"><div><h3>{t.name}</h3><em>{t.role}</em></div><p>{t.email}</p><small>{t.access}</small></div></article>)}<div className="teamInvite"><h3>Add manager</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Manager name"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Manager email / mobile"/><button disabled={!name||!email} onClick={()=>{setTeam(t=>[...t,{id:`T-${String(t.length+1).padStart(3,'0')}`,name,email,role:'Manager',access:'Jobs + Candidates + Chat'}]);setName('');setEmail('')}}><Plus size={17}/> Add Manager</button></div></section>}
function PostJob({onBack,onCreate}){const [title,setTitle]=useState('');const [location,setLocation]=useState('');const [vacancies,setVacancies]=useState(1);return <section className="postPage"><button className="back" onClick={onBack}>← Back</button><h2>Post a new job</h2><p className="formIntro">Simple form. Your ₹300 listing becomes active after payment.</p><label>Job title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Waiter, Machine Operator"/></label><label>Work location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Area / locality"/></label><label>Number of vacancies<input type="number" min="1" value={vacancies} onChange={e=>setVacancies(Number(e.target.value))}/></label><button className="continue" disabled={!title||!location} onClick={()=>onCreate({title,location,vacancies})}>Continue to ₹300 payment <ChevronRight size={18}/></button></section>}
