import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin,Search,Bell,Briefcase,Users,ChevronRight,Navigation} from 'lucide-react';
import './styles.css';
const locations=[
 {name:'Andheri East',left:25,top:24,count:42,skills:'Waiter 16 · Cook 9 · Helper 7'},
 {name:'Powai',left:48,top:42,count:28,skills:'Electrician 10 · Driver 7 · Cook 5'},
 {name:'Bandra West',left:69,top:62,count:19,skills:'Waiter 8 · Cook 5 · Helper 3'},
 {name:'Kurla',left:36,top:54,count:15,skills:'Driver 6 · Helper 5 · Waiter 3'},
 {name:'Goregaon',left:80,top:29,count:11,skills:'Waiter 4 · Cook 3 · Driver 2'}
];
const jobs=[{title:'Waiter',company:'Premium Family Restaurant',area:'Andheri East',salary:'₹18,000–₹22,000',tag:'New job'},{title:'Electrician',company:'Construction Company',area:'Powai',salary:'₹20,000–₹28,000',tag:'Urgent'},{title:'Cook',company:'Hotel & Restaurant',area:'Bandra West',salary:'₹22,000–₹30,000',tag:'Job for women'}];
const skills=[['Waiter',42],['Cook',28],['Electrician',19],['Driver',15]];
function App(){const[selected,setSelected]=useState(null);return <main className="app"><header><div><div className="brand">Mumbai Jobz</div><div className="tagline">Find work. Find people. Nearby.</div></div><button className="icon"><Bell size={20}/><span>3</span></button></header><section className="hero"><div className="mapTop"><strong>Jobs near you</strong><div className="mapCount"><Briefcase size={16}/> 115 jobs</div></div><div className="map"><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="area a1">Andheri</div><div className="area a2">Powai</div><div className="area a3">Bandra</div>{locations.map(p=><button className={`pin ${selected?.name===p.name?'selected':''}`} style={{left:`${p.left}%`,top:`${p.top}%`}} onClick={()=>setSelected(p)} key={p.name}><MapPin size={17}/><b>{p.count}</b><small>{p.name}</small></button>)}{selected&&<div className="locationCard"><div><b>{selected.name}</b><span>{selected.count} jobs</span></div><p>{selected.skills}</p><button onClick={()=>setSelected(null)}>×</button></div>}<button className="locate"><Navigation size={17}/></button></div><div className="skillRow">{skills.map(([s,c])=><div className="skill" key={s}><b>{c}</b><span>{s}</span></div>)}</div></section><div className="search"><Search size={19}/><input placeholder="Search jobs, skills or area"/><button>Search</button></div><section className="jobs"><div className="sectionTitle"><div><h2>Newly listed jobs</h2><p>Fresh opportunities around Mumbai</p></div><button className="see">See all <ChevronRight size={17}/></button></div>{jobs.map(j=><article className="job" key={j.title+j.area}><div className="jobIcon"><Briefcase size={20}/></div><div className="jobMain"><div className="jobHead"><h3>{j.title}</h3><em>{j.tag}</em></div><p>{j.company}</p><div className="meta"><span><MapPin size={14}/>{j.area}</span><strong>{j.salary}</strong></div></div></article>)}</section><nav><button className="active"><MapPin size={20}/><span>Jobs Map</span></button><button><Briefcase size={20}/><span>My Jobs</span></button><button><Bell size={20}/><span>Alerts</span></button><button><Users size={20}/><span>Profile</span></button></nav></main>}
createRoot(document.getElementById('root')).render(<App/>);