import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {MapPin,Search,Bell,Briefcase,Users,ChevronRight,Navigation,MessageCircle,ShieldCheck} from 'lucide-react';
import {getActiveJobs,aggregateByArea,aggregateBySkill} from './data/jobs';
import EmployerDashboard from './employer/EmployerDashboard';
import CandidatePipeline from './employer/CandidatePipeline';
import './styles.css';
const activeJobs=getActiveJobs(); const areaStats=aggregateByArea(activeJobs); const skillStats=aggregateBySkill(activeJobs);
const areaPositions={Andheri:{left:25,top:24},'Andheri East':{left:25,top:24},Powai:{left:48,top:42},'Bandra West':{left:69,top:62},Kurla:{left:36,top:54},Goregaon:{left:80,top:29}};
const locations=Object.values(areaStats).map(s=>({...s,...(areaPositions[s.area]||{left:50,top:50})}));
const newest=[...activeJobs].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,3); const skillList=Object.entries(skillStats).sort((a,b)=>b[1]-a[1]).slice(0,4);
function PublicHome(){const[selected,setSelected]=useState(null);const selectedJobs=useMemo(()=>selected?activeJobs.filter(j=>j.area===selected.area):[],[selected]);return <main className="app"><header><div><div className="brand">Mumbai Jobz</div><div className="tagline">Find work. Find people. Nearby.</div></div><button className="icon"><Bell size={20}/><span>3</span></button></header><section className="hero"><div className="mapTop"><strong>Jobs near you</strong><div className="mapCount"><Briefcase size={16}/> {activeJobs.length} jobs</div></div><div className="map"><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="area a1">Andheri</div><div className="area a2">Powai</div><div className="area a3">Bandra</div>{locations.map(p=><button className={`pin ${selected?.area===p.area?'selected':''}`} style={{left:`${p.left}%`,top:`${p.top}%`}} onClick={()=>setSelected(p)} key={p.area}><MapPin size={17}/><b>{p.total}</b><small>{p.area}</small></button>)}{selected&&<div className="locationCard"><div><b>{selected.area}</b><span>{selected.total} jobs</span></div><p>{Object.entries(selected.skills).map(([s,c])=>`${s} ${c}`).join(' · ')}</p>{selectedJobs.slice(0,2).map(j=><div className="miniJob" key={j.id}>{j.title} · ₹{j.salaryMin.toLocaleString()}–₹{j.salaryMax.toLocaleString()}</div>)}<button onClick={()=>setSelected(null)}>×</button></div>}<button className="locate"><Navigation size={17}/></button></div><div className="skillRow">{skillList.map(([s,c])=><div className="skill" key={s}><b>{c}</b><span>{s}</span></div>)}</div></section><div className="search"><Search size={19}/><input placeholder="Search jobs, skills or area"/><button>Search</button></div><section className="jobs"><div className="sectionTitle"><div><h2>Newly listed jobs</h2><p>Fresh opportunities around Mumbai</p></div><button className="see">See all <ChevronRight size={17}/></button></div>{newest.map(j=><article className="job" key={j.id}><div className="jobIcon"><Briefcase size={20}/></div><div className="jobMain"><div className="jobHead"><h3>{j.title}</h3><em>{j.tags[0]||'Active'}</em></div><p>{j.area}</p><div className="meta"><span><MapPin size={14}/>{j.area}</span><strong>₹{j.salaryMin.toLocaleString()}–₹{j.salaryMax.toLocaleString()}</strong></div></div></article>)}</section><nav><button className="active"><MapPin size={20}/><span>Jobs Map</span></button><button><Briefcase size={20}/><span>My Jobs</span></button><button><Bell size={20}/><span>Alerts</span></button><button><Users size={20}/><span>Profile</span></button></nav></main>}
function App(){const [mode,setMode]=useState('public'); if(mode==='employer') return <><button className="modeSwitch" onClick={()=>setMode('public')}>← Public site</button><EmployerDashboard/></>; if(mode==='pipeline') return <><button className="modeSwitch" onClick={()=>setMode('employer')}>← Employer dashboard</button><CandidatePipeline/></>; return <><PublicHome/><div className="devEntry"><button onClick={()=>setMode('employer')}><Briefcase size={17}/> Employer</button><button onClick={()=>setMode('pipeline')}><Users size={17}/> Candidate pipeline</button></div></>}
createRoot(document.getElementById('root')).render(<App/>);